#Srpring security
ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead1224service'
  auth:
    jwtSecret: VkXp2s5v8y/B?E(H+MbQeThWmZq3t6w9z$C&F)J@NcRfUjXn2r5u7x!A%D*G-KaP
    jwtExpirationMs: 14400000   


eureka:
  client:
    service-url:
      defaultZone: 'https://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@ead-serviceregistry-production.herokuapp.com/eureka'
  instance:
    hostname: ${APP_DOMAIN_NAME}
    non-secure-port: 80