server:
  port: 8089
  servlet:
    context-path: '/ead-payment/'

spring:
  application:
    name: ead-payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-payment
    username: postgres
    password: 1224
  cloud:
    config:
      enabled: true
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
    #config: false

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:lob: non_contextual_creation: true
    show_sql: true
    properties:
      hibernate:
       format_sql: true
    open-in-view: false
    generate-ddl: true
  output:
    ansi:
      enabled: Always  
  rabbitmq:
    addresses: amqps://opsazktl:pjGwggbKPiZQ8eOzUD2LXjjjM7yU2Y-B@moose.rmq.cloudamqp.com/opsazktl


#colorir mensagens no terminal windows
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    web: DEBUG
    org.hibernate: INFO

ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead1224service'
  auth:
    jwtSecret: t7w!z%C*F-JaNdRgUkXp2s5v8x/A?D(G+KbPeShVmYq3t6w9z$B&E)H@McQfTjWn
    jwtExpirationMs: 14400000
  api:
    url:
      course: 'http://ead-course-service/ead-course'
  broker:
    exchange:
      userEventExchange: ead.userevent
      paymentCommandExchange: ead.paymentcommand
    queue:
      userEventQueue:
        name: ead.userEvent.ms.payment
      paymentCommandQueue:
        name: ead.paymentcommand.ms.payment
    key:
      paymentCommandKey: ms.payment
  stripe:
     secretKey: '{cipher}78b245ed2c90264248cb64b1bc015ff2adc12588211b8b857940a6b84f9024e8a70563ac4c49997a5d99705c451e0d7058a1db152eb3f4706d1ccc014594e77f12fccab6f1bb4a29c0656e570da2c70a0298d5ab3376ad149ccdabba6ad17d59384fb059b2c059682eec95bdc4cc1d31b41c92978ed875199cf2369fa72657e1ef3cb106a5ef23c0185b2bda7b891e75'


#Configuração do resilliebce4j a nivel de método. criamos as instancias(name) ex:curcuitbreakerInstance, retryIntance
#O retry é uma das possibilidades de implementação de um broker. temos o circuitbreaker tambem
resilience4j:
  circuitbreaker:
    instances:
      curcuitbreakerInstance:
        slidingWindowSize: 30 #para cada 30 tentativas
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2 # após duas chamadas, ele levará em conta a porcentagem de falhas
        waitDurationInOpenState: 30s # período de tempo que o circuto fica em um certo estado, depois muda
        failureRateThreshold: 80  #porcentagem aceita de falhas
  retry:
    instances:
      retryIntance:
        maxAttempts: 3
        waitDuration: 5s


